# Form implementation generated from reading ui file 'Gui/Main.ui'
#
# Created by: PyQt6 UI code generator 6.0.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuReports = QtWidgets.QMenu(self.menubar)
        self.menuReports.setObjectName("menuReports")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuFInd_Device = QtWidgets.QMenu(self.menuSettings)
        self.menuFInd_Device.setObjectName("menuFInd_Device")
        self.menudevice = QtWidgets.QMenu(self.menubar)
        self.menudevice.setObjectName("menudevice")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_New_cofig = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Gui\\../../../../Downloads/BlackArch_logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.action_New_cofig.setIcon(icon)
        self.action_New_cofig.setObjectName("action_New_cofig")
        self.actionOpen_config = QtGui.QAction(MainWindow)
        self.actionOpen_config.setObjectName("actionOpen_config")
        self.actionClose = QtGui.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionNew_Device = QtGui.QAction(MainWindow)
        self.actionNew_Device.setObjectName("actionNew_Device")
        self.actionMobile_Device = QtGui.QAction(MainWindow)
        self.actionMobile_Device.setObjectName("actionMobile_Device")
        self.actionDoc = QtGui.QAction(MainWindow)
        self.actionDoc.setObjectName("actionDoc")
        self.actionupload_confing = QtGui.QAction(MainWindow)
        self.actionupload_confing.setObjectName("actionupload_confing")
        self.menuFile.addAction(self.action_New_cofig)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionOpen_config)
        self.menuFInd_Device.addAction(self.actionNew_Device)
        self.menuFInd_Device.addSeparator()
        self.menuFInd_Device.addAction(self.actionMobile_Device)
        self.menuSettings.addAction(self.menuFInd_Device.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionDoc)
        self.menudevice.addAction(self.actionupload_confing)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuReports.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menudevice.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuReports.setTitle(_translate("MainWindow", "Reports"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuFInd_Device.setTitle(_translate("MainWindow", "Find Device"))
        self.menudevice.setTitle(_translate("MainWindow", "Device"))
        self.action_New_cofig.setText(_translate("MainWindow", "&New config"))
        self.action_New_cofig.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionOpen_config.setText(_translate("MainWindow", "Open config"))
        self.actionOpen_config.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionNew_Device.setText(_translate("MainWindow", "New Device"))
        self.actionMobile_Device.setText(_translate("MainWindow", "Mobile Device"))
        self.actionDoc.setText(_translate("MainWindow", "&Doc"))
        self.actionupload_confing.setText(_translate("MainWindow", "upload confing"))
        self.actionupload_confing.setShortcut(_translate("MainWindow", "Ctrl+Alt+U"))
